// order types
export const FETCHING_MY_ORDER = 'FETCHING_MY_ORDER';
export const FETCHING_MY_ORDER_SUCCESS = 'FETCHING_MY_ORDER_SUCCESS';
export const FETCHING_MY_ORDER_ERROR = 'FETCHING_MY_ORDER_ERROR';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

// auth types
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';

// cart types
export const SAVE_NEW_CART = 'SAVE_NEW_CART';
export const MODIFY_CART = 'MODIFY_CART';

// loading types
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

// restaurant types
/* eslint-disable import/prefer-default-export */
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT';
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS';
export const FETCHING_RESTAURANT_ERROR = 'FETCHING_RESTAURANT_ERROR';

export const FETCHING_RESTAURANT_BY_ID = 'FETCHING_RESTAURANT_BY_ID';
export const FETCHING_RESTAURANT_BY_ID_SUCCESS =
  'FETCHING_RESTAURANT_BY_ID_SUCCESS';
export const FETCHING_RESTAURANT_BY_ID_ERROR =
  'FETCHING_RESTAURANT_BY_ID_ERROR';
export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT';
export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS';
export const SEARCH_RESTAURANT_ERROR = 'SEARCH_RESTAURANT_ERROR';

// notification types
export const FETCHING_NOTIFICATION = 'FETCHING_NOTIFICATION';
export const FETCHING_NOTIFICATION_SUCCESS = 'FETCHING_NOTIFICATION_SUCCESS';
export const FETCHING_NOTIFICATION_ERROR = 'FETCHING_NOTIFICATION_ERROR';

// other types
export const GET_DEVICE_TOKEN = 'GET_DEVICE_TOKEN';
