// order types
export const FETCHING_MY_ORDER = 'FETCHING_MY_ORDER';
export const FETCHING_MY_ORDER_SUCCESS = 'FETCHING_MY_ORDER_SUCCESS';
export const FETCHING_MY_ORDER_ERROR = 'FETCHING_MY_ORDER_ERROR';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCES';
export const GET_ORDER_BY_ID_ERROR = 'GET_ORDER_BY_ID_ERROR';
export const CLEAR_ORDER_INFO = 'CLEAR_ORDER_INFO';
export const REVIEW_ORDER = 'REVIEW_ORDER';
export const REVIEW_ORDER_SUCCESS = 'REVIEW_ORDER_SUCCESS';
export const REVIEW_ORDER_ERROR = 'REVIEW_ORDER_ERROR';

// auth types
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

// user types
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_ERROR = 'UPDATE_USER_INFO_ERROR';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
export const BOOKMARK = 'BOOKMARK';
export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
export const BOOKMARK_ERROR = 'BOOKMARK_ERROR';

// cart types
export const SAVE_NEW_CART = 'SAVE_NEW_CART';
export const MODIFY_CART = 'MODIFY_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const DELETE_CART = 'DELETE_CART';

// loading types
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

// restaurant types
/* eslint-disable import/prefer-default-export */
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT';
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS';
export const FETCHING_RESTAURANT_ERROR = 'FETCHING_RESTAURANT_ERROR';
export const FETCHING_RESTAURANT_BY_ID = 'FETCHING_RESTAURANT_BY_ID';
export const FETCHING_RESTAURANT_BY_ID_SUCCESS =
  'FETCHING_RESTAURANT_BY_ID_SUCCESS';
export const FETCHING_RESTAURANT_BY_ID_ERROR =
  'FETCHING_RESTAURANT_BY_ID_ERROR';
export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT';
export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS';
export const SEARCH_RESTAURANT_ERROR = 'SEARCH_RESTAURANT_ERROR';
export const CLEAR_REST_INFO = 'CLEAR_REST_INFO';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const FETCHING_REVIEW = 'FETCHING_REVIEW';
export const FETCHING_REVIEW_SUCCESS = 'FETCHING_REVIEW_SUCCESS';
export const FETCHING_REVIEW_ERROR = 'FETCHING_REVIEW_ERROR';

// notification types
export const FETCHING_NOTIFICATION = 'FETCHING_NOTIFICATION';
export const FETCHING_NOTIFICATION_SUCCESS = 'FETCHING_NOTIFICATION_SUCCESS';
export const FETCHING_NOTIFICATION_ERROR = 'FETCHING_NOTIFICATION_ERROR';

// other types
export const GET_DEVICE_TOKEN = 'GET_DEVICE_TOKEN';
